import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/component/Header";
import PropertyPrices from "@/component/PropertyPrices";
import AmenitiesSection from "@/component/AmenitiesSection";
import BanksSection from "@/component/BanksSection";
import PropertyDetails from "@/component/PropertyDetails";
import UnitLayouts from "@/component/UnitLayouts";
import FloorPlans from "@/component/FloorPlans";
import MasterLayout from "@/component/MasterLayout";
import LocationMap from "@/component/LocationMap";
import ContentSection from "@/component/ContentSection";
import Footer from "@/component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <PropertyPrices />
        <PropertyDetails />
        <AmenitiesSection />
        <UnitLayouts />
        <FloorPlans />
        <MasterLayout />
        <BanksSection />
        <LocationMap />
        <ContentSection />
        <Footer />
      </body>
    </html>
  );
}
